- name: CONFIG FW POLICIES
  hosts: FortiManager
  connection: httpapi
  gather_facts: False

  tasks:

  - name: ADD POLICIES
    fmgr_fwpol_ipv4:
      mode: "set"
      adom: "{{ item.value.adom }}"
      package_name: "{{ item.value.package_name }}"
      name: "{{ item.value.name }}"
      comments: "Created by Ansible"
      action: "{{ item.value.action }}"
      dstaddr: "{{ item.value.dst }}"
      srcaddr: "{{ item.value.src }}"
      dstintf: "{{ item.value.dstint }}"
      srcintf: "{{ item.value.srcint }}"
      logtraffic: "{{ item.value.log }}"
      service: "{{ item.value.service }}"
      schedule: "always"
    ignore_errors: yes
    ignore_unreachable: yes
    with_dict: "{{ rules }}"
